### ISSUE TITLE
release for JMX Reporter

### ISSUE THREAD

**Issue by lobeck** [staslev/storm-metrics-reporter#3]
Hi,

the JMX reporter was added a while back, but there hasn't been a release since.

Could you please create one, so we don't have to use local jars?

Thanks,
Cheers!

**Comment by staslev** [comment]
Hi,

You're right, it's been a while.

Hopefully I'll be able to give it a look this weekend...

**Comment by lobeck** [comment]
Thanks for checking! It would be awesome too, if you could integrate https://github.com/indigodp/storm-metrics-reporter/commit/5d35ed8810ffdb409a085c421ed7e48ff8277ba7 as well

**Comment by staslev** [comment]
Hmm... I'll need a PR to get it in.

**Comment by lobeck** [comment]
Here you go: https://github.com/staslev/storm-metrics-reporter/pull/4

**Comment by staslev** [comment]
Thanks.

Btw, did you try running it with `Storm 1.0.1`?

**Comment by lobeck** [comment]
Today we've added it to our 1.0.2 staging cluster and were able to extract 4k datapoints, so at least it's running. But we haven't taken a deeper look yet, as we've had some struggles to get it running at all. Will probably post some docs here once we've got it fully integrated with everything.

**Comment by staslev** [comment]
Cool, looking forward to your posts.

**Comment by staslev** [comment]
@lobeck , I've released a snapshot version with your pull request and JMX in (from a private PR branch). 

Mind giving it a try? 
If things look good, I'll merge (and release) and hopefully add some tests that test the actual metrics mechanism in light of the move to `1.x`.

``` xml
<dependency>
  <groupId>com.github.staslev</groupId>
  <artifactId>storm-metrics-reporter</artifactId>
  <version>1.5.0-SNAPSHOT</version>
</dependency>
```

You might need to add this to your `pom.xml`:

``` xml
<repositories>
    <repository>
      <id>oss.sonatype.org-snapshot</id>
      <url>http://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
</repositories>
```

**Comment by lobeck** [comment]
Just deployed it without any issues. Anything special we need to test?

**Comment by staslev** [comment]
Nothing in particular, just wanted to make sure things play nice and metrics are sent since it hasn't really been battle tested with `Storm 1.x` (as opposed to `Storm 0.9`).

Let me know if things look good and if so I'll get version `1.5` out.

**Comment by lobeck** [comment]
Ok, we're running it for a while now and haven't seen any issues.

**Comment by staslev** [comment]
Cool, thanks for checking.
I'll ping you once I have the new version in maven central.

**Comment by staslev** [comment]
The new version is out:

``` xml
<dependency>
  <groupId>com.github.staslev</groupId>
  <artifactId>storm-metrics-reporter</artifactId>
  <version>1.5.0</version>
</dependency>
```

Feel free to let me now how it goes.
